allowBuilds:
  core-js: true
  simple-git-hooks: true
minimumReleaseAgeExclude:
  - '@types/node@25.9.3'
  - '@vue/compiler-core@3.5.37'
  - '@vue/compiler-dom@3.5.37'
  - '@vue/compiler-sfc@3.5.37'
  - '@vue/compiler-ssr@3.5.37'
  - '@vue/reactivity@3.5.37'
  - '@vue/runtime-core@3.5.37'
  - '@vue/runtime-dom@3.5.37'
  - '@vue/server-renderer@3.5.37'
  - '@vue/shared@3.5.37'
  - vue@3.5.37
